package rsaencryption;

import java.math.BigInteger;

/**
 * This final static class stores key data generated by KeySet
 * @author Ryan N May
 * @since 2023-04-24
 */
public final class Key implements java.io.Serializable 
{
	public BigInteger element1;
	public BigInteger element2;
	
	Key(BigInteger _element1, BigInteger _element2)
	{
		this.element1 = _element1;
		this.element2 = _element2;
	}
}
